CREATE TABLE MATERIA(
     CODIGO INT,
     ALUMNO VARCHAR(30),
	 NOMBRE VARCHAR(30),
     CALIFICACION INT
)

INSERT INTO MATERIA(CODIGO, ALUMNO, NOMBRE, CALIFICACION) VALUES
(1,'MATEMATICAS','JOVANY NOGUEZ',7),
(2,'INGLES','JOVANY NOGUEZ',9),
(3,'TUTORIA','JOVANY NOGUEZ',8),
(4,'CON_ENERGÍA','DANIELA NOGUEZ',8),
(5,'ESPAÑOL','ANGEL PALACIOS',8),
(6,'TALLER','CRISTOPHER OTHON',9),
(7,'CULTURA','ARIADNA GONZALES',10),
(8,'EDUCACION FISICA','VICTOR HERNANDEZ',10),
(9,'CIENCIAS SOCIALES','KIMBERLY NOGUEZ',10),
(10,'HISTORIA','DANIEL FELIX',10)